
const ACTION_TYPE = {
	LOGIN: 'LOGIN',
	LOG_OUT: 'LOG_OUT',
	LOAD_PROGRESS: 'LOAD_PROGRESS',
	SHOW_SNACK: 'SHOW_SNACK',
	
	FETCH_CONSTITUENCY: 'FETCH_CONSTITUENCY',
	SEARCH_CONSTITUENCY: 'SEARCH_CONSTITUENCY',
	
	FETCH_SUB_COUNTY: 'FETCH_SUB_COUNTY',
	SEARCH_SUB_COUNTY: 'SEARCH_SUB_COUNTY',
	
	FETCH_PARISH: 'FETCH_PARISH',
	SEARCH_PARISH: 'SEARCH_PARISH',
	
	FETCH_VILLAGE: 'FETCH_VILLAGE',
	SEARCH_VILLAGE: 'SEARCH_VILLAGE',
	
	FETCH_REPRESENTATIVE: 'FETCH_REPRESENTATIVE',
	SEARCH_REPRESENTATIVE: 'SEARCH_REPRESENTATIVE',
	
	FETCH_USERS: 'FETCH_USERS',
	SEARCH_USERS: 'SEARCH_USERS'
};

export default ACTION_TYPE;
